package ru.ivmiit.azat.numericalmethods.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYDataset;
import ru.ivmiit.azat.numericalmethods.graph.SimpleLine;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import java.awt.*;
import java.util.*;
import java.util.List;

public class LineAnimatedGraphChart extends AbstractLineGraphChart {
    private JPanel contentPane;
    private JSlider aParamSlider;
    private JPanel graphicPanel;
    private JLabel aValueTextField;
    private JLabel aValueDescriptionTextField;
    private JLabel maxTimeDescriptionTextField;
    private JLabel maxTimeTextField;
    private JSlider maxTimeSlider;
    private LinkedHashMap<Double, List<SimpleLine>> simpleLinesOfA;

    public LineAnimatedGraphChart(LinkedHashMap<Double, List<SimpleLine>> simpleLinesOfA, String xName, String yName, String title, boolean isLine) {
        super(new ArrayList<>(), xName, yName, title, isLine);
        this.simpleLinesOfA = simpleLinesOfA;

        setContentPane(contentPane);
        setModal(true);
        setTitle("Animated line chart");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        aParamSlider.setMinimum(0);
        aParamSlider.setMaximum(simpleLinesOfA.size() - 1);
        aParamSlider.setValue(0);

        setChartPanel(createChartPanel());
        graphicPanel.add(getChartPanel());

        if (simpleLinesOfA.size() > 0) {
            setSimpleLineValue(0);
        }

        this.aParamSlider.addChangeListener(this::changeSimpleLine);
        this.maxTimeSlider.addChangeListener(this::changeMaxTime);
    }

    private void changeMaxTime(ChangeEvent changeEvent) {
        JSlider source = (JSlider) changeEvent.getSource();
        int elementNumber = source.getValue();
        Double maxTime = getSimpleLines().get(0).getTime().get(elementNumber);
        setMaxTime(maxTime);
        maxTimeTextField.setText(getMaxTime().toString());
        updateChartPanel();
    }

    private void updateChartPanel() {
        XYDataset dataset = createDataset();
        JFreeChart chart = createChart(dataset);
        getChartPanel().setChart(chart);
    }

    private void changeSimpleLine(ChangeEvent changeEvent) {
        JSlider source = (JSlider) changeEvent.getSource();
        int elementNumber = source.getValue();
        setSimpleLineValue(elementNumber);
    }

    private void setSimpleLineValue(int index) {
        simpleLinesOfA.entrySet().stream().skip(index).findFirst().ifPresent(e -> {
            aValueTextField.setText(e.getKey().toString());
            setSimpleLines(e.getValue());
            maxTimeSlider.setMinimum(0);
            maxTimeSlider.setMaximum(e.getValue().get(0).getTime().size() - 1);
            setMaxTime(e.getValue().get(0).getTime().get(e.getValue().get(0).getTime().size() - 1));
            maxTimeSlider.setValue(maxTimeSlider.getMaximum());
            maxTimeTextField.setText(getMaxTime().toString());
            updateChartPanel();
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        contentPane.setEnabled(true);
        graphicPanel = new JPanel();
        graphicPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(graphicPanel, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        contentPane.add(panel1, gbc);
        aValueTextField = new JLabel();
        aValueTextField.setText("0.0");
        panel1.add(aValueTextField, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 0, false));
        aValueDescriptionTextField = new JLabel();
        aValueDescriptionTextField.setText("Значение δ:");
        panel1.add(aValueDescriptionTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        aParamSlider = new JSlider();
        aParamSlider.setValue(0);
        panel1.add(aParamSlider, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel2, gbc);
        maxTimeSlider = new JSlider();
        maxTimeSlider.setValue(100);
        panel2.add(maxTimeSlider, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        maxTimeDescriptionTextField = new JLabel();
        maxTimeDescriptionTextField.setText("Максимальное время t");
        panel2.add(maxTimeDescriptionTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        maxTimeTextField = new JLabel();
        maxTimeTextField.setText("50.0");
        panel2.add(maxTimeTextField, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, -1), new Dimension(100, -1), new Dimension(100, -1), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
